datasets_dir : /home/vatsal/NWM/earth-forecasting-transformer/datasets

seq_len: 25
sample_mode: "sequent"
stride: 12
batch_size: 1
layout: "NHWT"
preprocess: true
rescale_method: "01"
verbose: false

# datamodule_only
dataset_name: "sevir"
start_date: [2017, 1, 1]  # or [YYYY, MM, DD] if known
train_val_split_date: [2019, 1, 1]
train_test_split_date: [2019, 5, 1]
end_date: null  # or [YYYY, MM, DD] if known
num_workers: 4
