backbone: earthformer
batch_size: 4
ckpt_milestone: null
dataset: custom
early_stop: 10
ema_rate: 0.95
epochs: 10
eval: false
exp_dir: basic_exps
exp_note: null
frames_in: 10
frames_out: 10
grad_acc_step: 1
img_channel: 1
img_size: 128
l2_norm: 0.0
lr: 0.0001
lr_beta1: 0.9
lr_beta2: 0.95
mixed_precision: 'no'
num_workers: 4
scheduler: cosine
seed: 0
seq_len: 20
training_steps: 20
use_diff: false
wandb_state: online
warmup_steps: 1000
