backbone: earthformer
batch_size: 16
ckpt_milestone: null
dataset: sevir
early_stop: 10
ema_rate: 0.95
epochs: 2
eval: false
exp_dir: basic_exps
exp_note: null
frames_in: 13
frames_out: 12
grad_acc_step: 1
img_channel: 1
img_size: 384
l2_norm: 0.0
lr: 0.0001
lr_beta1: 0.9
lr_beta2: 0.95
mixed_precision: bf16
num_workers: 2
scheduler: cosine
seed: 0
seq_len: 25
training_steps: 200
use_diff: false
wandb_state: disabled
warmup_steps: 1000
