_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
                - 83
                - 103
            "3":
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
backbone:
    value: earthformer
batch_size:
    value: 1
ckpt_milestone:
    value: null
dataset:
    value: sevir
early_stop:
    value: 10
ema_rate:
    value: 0.95
epochs:
    value: 1
eval:
    value: false
exp_dir:
    value: basic_exps
exp_note:
    value: null
frames_in:
    value: 10
frames_out:
    value: 10
grad_acc_step:
    value: 1
img_channel:
    value: 1
img_size:
    value: 384
l2_norm:
    value: 0
lr:
    value: 0.0001
lr_beta1:
    value: 0.9
lr_beta2:
    value: 0.95
mixed_precision:
    value: bf16
num_workers:
    value: 2
scheduler:
    value: cosine
seed:
    value: 0
seq_len:
    value: 20
training_steps:
    value: 20
use_diff:
    value: true
wandb_state:
    value: online
warmup_steps:
    value: 1000
