Model:
  input_size: 48
  in_channels: 8
  mlp_ratio: 4.0
  learn_sigma: False
  out_channels: 48
  split_num: 12
  num_heads: 16
  single_heads_num: 4
  hidden_size: 1152
  enc_hidden_size: 256
  patch_size: 2
  enc_depth: 12
  latent_depth: 12 

timesteps: 100
