Model:
  input_size: 128
  in_channels: 2
  mlp_ratio: 4.0
  learn_sigma: False
  out_channels: 4
  split_num: 4
  num_heads: 16
  single_heads_num: 4
  hidden_size: 512
  enc_hidden_size: 32
  patch_size: 32
  enc_depth: 8
  latent_depth: 12 

timesteps: 250