Model:
 input_shape: [21, 128, 128, 1]
 target_shape: [10, 128, 128, 1]
 base_units: 128
 block_units: null
 scale_alpha: 1.0

 enc_depth: [2, 2]
 dec_depth: [2, 2]
 enc_use_inter_ffn: true
 dec_use_inter_ffn: true
 dec_hierarchical_pos_embed: true

 downsample: 2
 downsample_type: patch_merge
 upsample_type: upsample

 num_global_vectors: 16
 use_dec_self_global: true
 dec_self_update_global: true
 use_dec_cross_global: true
 use_global_vector_ffn: true
 use_global_self_attn: false
 separate_global_qkv: false
 global_dim_ratio: 1

 self_pattern: axial
 cross_self_pattern: axial
 cross_pattern: cross_1x1
 dec_cross_last_n_frames: null

 attn_drop: 0.1
 proj_drop: 0.1
 ffn_drop: 0.1
 num_heads: 8

 ffn_activation: gelu
 gated_ffn: false
 norm_layer: layer_norm
 padding_type: zeros
 pos_embed_type: "t+hw"
 use_relative_pos: true
 self_attn_use_final_proj: true
 dec_use_first_self_attn: false

 z_init_method: zeros
 checkpoint_level: 2

 initial_downsample_type: stack_conv
 initial_downsample_activation: leaky
 initial_downsample_stack_conv_num_layers: 3
 initial_downsample_stack_conv_dim_list: [8, 32, 128]
 initial_downsample_stack_conv_downscale_list: [3, 2, 2]
 initial_downsample_stack_conv_num_conv_list: [2, 2, 2]

 attn_linear_init_mode: "0"
 ffn_linear_init_mode: "0"
 conv_init_mode: "0"
 down_up_linear_init_mode: "0"
 norm_init_mode: "0"
   
timesteps: 1000